[package]
name = "simple-http-cache"
version = "0.1.0"
authors = ["Tim Allen <screwtape@froup.com>"]

[dependencies]
crypto-hash = "0.3.0"
log = "0.3.8"
reqwest = "0.8.0"
sqlite = "0.23.9"

[dev-dependencies]
tempdir = "0.3.5"
