[package]
name = "static-http-cache"
version = "0.1.0"
authors = ["Tim Allen <screwtape@froup.com>"]

[dependencies]
crypto-hash = "0.3.0"
log = "0.4.1"
reqwest = "0.8.4"
sqlite = "0.23.9"
rand = "0.4.2"

[dev-dependencies]
tempdir = "0.3.5"
env_logger = "0.5.3"
